### ISSUE TITLE
Division by zero error with no swap

### ISSUE THREAD

**Issue by MGThePro** [MatthiasSchinzel/sysmon#1]
Since I have enough ram to not use swap, I currently don't have any swap, which leads to the following error message:
`Icon theme "gnome" not found.
Traceback (most recent call last):
  File "sysmon.py", line 589, in <module>
    main()
  File "sysmon.py", line 583, in main
    main = MainWindow()
  File "sysmon.py", line 109, in __init__
    self.plot_meminfo()
  File "sysmon.py", line 313, in plot_meminfo
    (swaptotal - swapfree)
ZeroDivisionError: division by zero`

**Comment by MatthiasSchinzel** [comment]
Thanks for submitting! I think I can push an update handling this case later today. 

Sorry for the inconvenience, I will let you know when an update is available!

**Comment by MatthiasSchinzel** [comment]
Please try again. I unmounted my swap and now it works for me. 

Swap entry will still shows up, I will remove this in a future update, as well as the red swap line.

**Comment by MGThePro** [comment]
works perfectly now :+1:
